version: '3'
services:
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - portfolio-node_modules:/app/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
volumes:
  portfolio-node_modules: